version: '3.5'

networks:
  prodnetwork:
    driver: bridge

volumes:
  nexus-data:
  jenkins-data:

services:
  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "18080:8080"
    networks:
      - prodnetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins-data:/var/lib/jenkins/
    depends_on:
      - sonar
    environment:
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432
  sonardb:
    networks:
      - prodnetwork
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
  sonar:
    image: sonarqube
    restart: always
    ports:
     - "19000:9000"
     - "19092:9092"
    networks:
      - prodnetwork
    depends_on:
      - sonardb
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'localhost'
    networks:
      - prodnetwork
    environment:
#https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2299
      GITLAB_OMNIBUS_CONFIG: |
         external_url 'http://localhost:19690'
         nginx['redirect_http_to_https'] = false
    ports:
      - '19690:19690'
      - "10080:80"
    volumes:
      - /opt/gitlab/config:/etc/gitlab
      - /opt/gitlab/logs:/var/log/gitlab
      - /opt/gitlab/data:/var/opt/gitlab
